apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway-ingress
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: perfilnet-apigateway-svc
                port:
                  number: 80
      host: apigateway.perfilnet.local
  tls:
    - hosts:
        - apigateway.perfilnet.local
      secretName: apigateway-secret